export const ADD_TAB = "ADD_TAB";
export const DELETE_TAB = "DELETE_TAB";
export const MODIFY_TAB = "MODIFY_TAB";
export const SET_TABS = "SET_TABS";
export const SET_COMMENT = "SET_COMMENT";
export const SET_COMMENT_RESPONSE = "SET_COMMENT_RESPONSE";
export const SET_RESPONSE_CONVERSATION = "SET_RESPONSE_CONVERSATION";